title: <p align="center"> Isha Sukhija </p>
logo: /assets/img/iiii.jpg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/isha-sukhija-4920ba27</a> |
  <a href="https://github.com/IshaSukhija">GitHub</a>
  Minimal is a theme for GitHub Pages.
  <br>   
  I'm working as senior developer with Data transformation team 
  with SAP LABs Pvt Ltd.
  Worked on multiple data transformation products adn involved 
  in end to end delivery of the same.
  <br>
  </p>
theme: jekyll-theme-minimal


